In [1]:
! pip freeze > requirements.txt

In [ ]:
! pip install -r requirements.txt

## 英文斷詞

In [2]:
s = 'this is a book'
s.split()

['this', 'is', 'a', 'book']

## Jieba
- C:\ProgramData\Anaconda3\Lib\site-packages\jieba

In [3]:
! pip install jieba

In [3]:
import jieba
s = '那酸民婉君也可以報名嗎?'
jieba.add_word('酸民')
jieba.add_word('婉君')
for w in jieba.cut(s):
    print(w)

那
酸民
婉君
也
可以
報名
嗎
?


In [8]:
import re
article = '''中央研究院院士、我國駐WTO代表團常任代表朱敬一撰文質疑，此次稅改股利分離課稅是圖利富人。總統蔡英文接受中央社專訪時指出，「尊重他的看法」，財政部也會再向朱敬一說明，不過稅改要看整體，不能只看一部分。她強調，稅改要減輕一般所得者和中小企業的負擔，希望讓受薪者和一般所得者「生活安全感好一點」，但整體稅收損失不能太大。'''
re.split('、|。|，|「|」', article)

['中央研究院院士',
 '我國駐WTO代表團常任代表朱敬一撰文質疑',
 '此次稅改股利分離課稅是圖利富人',
 '總統蔡英文接受中央社專訪時指出',
 '',
 '尊重他的看法',
 '',
 '財政部也會再向朱敬一說明',
 '不過稅改要看整體',
 '不能只看一部分',
 '她強調',
 '稅改要減輕一般所得者和中小企業的負擔',
 '希望讓受薪者和一般所得者',
 '生活安全感好一點',
 '',
 '但整體稅收損失不能太大',
 '']

In [1]:
import jieba

seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=True)
print("Full Mode:", "/ ".join(seg_list))

seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))


Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\User\AppData\Local\Temp\jieba.cache
Loading model cost 4.729 seconds.
Prefix dict has been built succesfully.


Full Mode: 大/ 巨蛋/ 案/ 對/ 市府/ 同仁/ 下/ 封口/ 封口令/ 口令/ / / / 柯/ P/ 否/ 認
Default Mode: 大/ 巨蛋/ 案對/ 市府/ 同仁/ 下/ 封口令/ ？/ 　/ 柯/ P/ 否認


In [2]:
#jieba.set_dictionary('userdict.txt')
jieba.load_userdict('userdict.txt')

In [3]:
import jieba
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))


Default Mode: 大巨蛋/ 案對/ 市府/ 同仁/ 下/ 封口令/ ？/ 　/ 柯P/ 否認


In [6]:
import jieba.posseg as pseg
jieba.load_userdict('userdict.txt')
for w in pseg.cut("大巨蛋案對市府同仁下封口令？　柯P否認"):
    print(w)

大巨蛋/x
案/ng
對/p
市府/n
同仁/nr
下/f
封口令/n
？/x
　/x
柯P/x
否認/v


In [7]:
sentence = "大巨蛋案對市府同仁下封口令？　柯P否認"
words = jieba.tokenize(sentence)

for tw in words:
    print(tw[0], tw[1], tw[2])

大巨蛋 0 3
案對 3 5
市府 5 7
同仁 7 9
下 9 10
封口令 10 13
？ 13 14
　 14 15
柯P 15 17
否認 17 19


## n-gram

In [9]:
s = '那我們酸民婉君也可以報名嗎?'
s[0:2]

'那我'

In [10]:
s = '那我們酸民婉君也可以報名嗎?'

for i in range(0, len(s) - 2 + 1):
    print(s[i:i+2])

那我
我們
們酸
酸民
民婉
婉君
君也
也可
可以
以報
報名
名嗎
嗎?


In [11]:
for i in range(0, len(s) - 3 + 1):
    print(s[i:i+3])

那我們
我們酸
們酸民
酸民婉
民婉君
婉君也
君也可
也可以
可以報
以報名
報名嗎
名嗎?


In [12]:
a = ['a', 'b', 'c', 'a', 'b']
from collections import Counter
c = Counter(a)
c

Counter({'a': 2, 'b': 2, 'c': 1})

In [13]:
from collections import Counter
def ngram(s, n = 2):
    words = []
    for i in range(0, len(s) - n + 1):
        words.append(s[i:i+n])
    c = Counter(words)
    return c

In [14]:
article = '''中央研究院院士、我國駐WTO代表團常任代表朱敬一撰文質疑，此次稅改股利分離課稅是圖利富人。總統蔡英文接受中央社專訪時指出，「尊重他的看法」，財政部也會再向朱敬一說明，不過稅改要看整體，不能只看一部分。她強調，稅改要減輕一般所得者和中小企業的負擔，希望讓受薪者和一般所得者「生活安全感好一點」，但整體稅收損失不能太大。
蔡總統指出，國民黨執政時，把公司營利事業所得稅降到17%、個人所得稅往上調，造成經濟發展需要的投資人和專業人員，在所得稅上負擔比較大，因此需要調整；另外，稅改也要減輕創新和中小型企業的負擔，同時顧慮到整體稅收的損失不能太大。
蔡總統表示，在這幾個原則下，稅改把營所稅從17%調高到20%，符合國際趨勢，不會太高；為了要讓創新和中小型企業減輕負擔，保留盈餘加徵營所稅則由10%降至5%。她說，大型企業在股市或資本市場集資比較容易，中小企業比較難，因此，讓中小企業的保留盈餘可做未來投資很重要。
蔡總統指出，經濟發展裡需要的高級專業人才薪資很高，但他們對經濟發展效能大，因此稍微降低他們的賦稅負擔，綜所稅從45%降到40%，希望留住人才，這也大致符合國際趨勢。蔡總統還說，稅改還讓一般所得者有比較大扣除額，如果受薪者和一般所得者的稅負擔減輕，增加可支配所得，生活安全感更好一點，比較願意消費。（政治中心／台北報導）'''

In [22]:
res = ngram(article, 3)
res.most_common(10)

[('，稅改', 4),
 ('一般所', 4),
 ('般所得', 4),
 ('所得者', 4),
 ('負擔，', 4),
 ('蔡總統', 4),
 ('指出，', 3),
 ('和中小', 3),
 ('中小企', 3),
 ('小企業', 3)]

In [34]:
import re
sentence_ary = re.split('、|，|」|「|。|；|／|\n|（|）', article)

In [37]:
s = '我國駐WTO代表團常任代表朱敬一撰文質疑'
#method 1
s.replace('朱敬一', '')

#method 2
''.join(s.split('朱敬一'))

'我國駐WTO代表團常任代表撰文質疑'

In [38]:
def removeKey(s, keywords):
    for keyword in keywords:
        s = s.replace(keyword , '')
    return s

s = '我國駐WTO代表團常任代表朱敬一撰文質疑'
removeKey(s, ['朱敬一', '代表團'])

'我國駐WTO常任代表撰文質疑'

In [40]:
def ngram(s, n = 2):
    words = []
    for i in range(0, len(s) - n + 1):
        words.append(s[i:i+n])
    return words
s = '我國駐WTO代表團常任代表朱敬一撰文質疑'
ngram(s, 2)

['我國',
 '國駐',
 '駐W',
 'WT',
 'TO',
 'O代',
 '代表',
 '表團',
 '團常',
 '常任',
 '任代',
 '代表',
 '表朱',
 '朱敬',
 '敬一',
 '一撰',
 '撰文',
 '文質',
 '質疑']

In [45]:
from collections import Counter
keywords = []

words = []
for sentence in sentence_ary:
    ngram_words = ngram(sentence, 4)
    words.extend(ngram_words)
c = Counter(words)
for k, v in c.items():
    if v >= 3:
        #print(k,v)
        keywords.append(k)

一般所得 4
般所得者 4
中小企業 3
經濟發展 3


In [48]:
from collections import Counter
keywords = []

for n in range(4,1,-1):
    words = []
    for sentence in sentence_ary:
        sentence = removeKey(sentence, keywords)
        ngram_words = ngram(sentence, n)
        words.extend(ngram_words)
    c = Counter(words)
    for k, v in c.items():
        if v >= 5:
            #print(k,v)
            keywords.append(k)
keywords

['稅改', '總統', '所得', '中小', '企業', '負擔', '比較']

## 長詞優先法完整實做

In [49]:
article = '''台積電董事長張忠謀日前曾說，他反對政府的五加二產業，並指政府只要做好基礎建設就好，不要管太多。總統蔡英文接受中央社專訪時首度回應指出，五加二計畫不是創造新產業，絕對不會是那種古老時代、國家在經濟發展的初期，挑幾個產業然後就說要發展。她還說，和平電廠鐵塔倒塌、815大停電等事件，嚴格來說，不是缺電的問題，而是天災與人為疏失。
蔡總統說，台灣過去有這樣的例子，例如，汽車產業是被挑出來的、半導體產業也是被挑出來的，有的成功，有的失敗；很多國家在經濟發展過程中，必須要把有限資源集中在幾個重要的產業上，讓它能夠快速成長，然後帶著經濟往前走，「我們確實已經脫離了那種模式，我們現在要做是在現有的產業基礎上，去讓它更有競爭力、更能夠轉型。」
蔡總統指出，五加二的基礎產業其實都已存在，而且是有相當規模的產業，智慧機械是最明顯例子，台灣的機械產業做得很好，ICT產業也做得很好，為何不在這個基礎上，鼓勵業者把兩者結合起來，就是下一個世代的智慧機械。她也強調，「政府不是指定你只能做這個，不能做那個」，而是在現有的產業基礎上，快速地讓產業升級，讓它可以移到下個階段的競爭力。
蔡總統表示，要發展這些產業，有些基礎工程，不是企業自己可以做得出來，那就是政府要做的，例如硬體的基礎設備、軟體的能力、數位的基礎建設，都要替企業備齊；因此，政府對於企業界在意的「五缺」（缺水、缺電、缺地、缺工、缺人才），十分重視，會積極處理，尤其對於缺電的議題。
蔡總統指出，和平電廠鐵塔倒塌、815大停電等事件，嚴格來說，不是缺電的問題，而是天災與人為疏失，它暴露整個供電系統的問題，包括輸電系統、人員嚴謹度等問題。她說，雖然一般認為備轉容量率大概7%或8%就夠，但這事件過後，她確實有拜託經濟部去考慮，把備轉容量拉到10%。（政治中心／台北報導）'''

In [58]:
import re

def ngram(s, n = 2):
    words = []
    for i in range(0, len(s) - n + 1):
        words.append(s[i:i+n])
    return words

def removeKey(s, keywords):
    for keyword in keywords:
        s = s.replace(keyword , '')
    return s



sentence_ary = re.split('、|，|」|「|。|；|／|\n|（|）', article)

keywords = []
for n in range(6,1,-1):
    words = []
    for sentence in sentence_ary:
        sentence = removeKey(sentence, keywords)
        ngram_words = ngram(sentence, n)
        words.extend(ngram_words)
    c = Counter(words)
    for k, v in c.items():
        if v >= 3:
            keywords.append(k)
keywords

['五加二',
 '缺電的',
 '的問題',
 '蔡總統',
 '的產業',
 '基礎上',
 '的基礎',
 '政府',
 '要做',
 '指出',
 '不是',
 '產業',
 '經濟',
 '發展',
 '事件',
 '問題',
 '而是',
 '出來',
 '讓它',
 '機械',
 '做得',
 '企業']

## 量化分析

In [59]:
article = '''中央研究院院士、我國駐WTO代表團常任代表朱敬一撰文質疑，此次稅改股利分離課稅是圖利富人。總統蔡英文接受中央社專訪時指出，「尊重他的看法」，財政部也會再向朱敬一說明，不過稅改要看整體，不能只看一部分。她強調，稅改要減輕一般所得者和中小企業的負擔，希望讓受薪者和一般所得者「生活安全感好一點」，但整體稅收損失不能太大。
蔡總統指出，國民黨執政時，把公司營利事業所得稅降到17%、個人所得稅往上調，造成經濟發展需要的投資人和專業人員，在所得稅上負擔比較大，因此需要調整；另外，稅改也要減輕創新和中小型企業的負擔，同時顧慮到整體稅收的損失不能太大。
蔡總統表示，在這幾個原則下，稅改把營所稅從17%調高到20%，符合國際趨勢，不會太高；為了要讓創新和中小型企業減輕負擔，保留盈餘加徵營所稅則由10%降至5%。她說，大型企業在股市或資本市場集資比較容易，中小企業比較難，因此，讓中小企業的保留盈餘可做未來投資很重要。
蔡總統指出，經濟發展裡需要的高級專業人才薪資很高，但他們對經濟發展效能大，因此稍微降低他們的賦稅負擔，綜所稅從45%降到40%，希望留住人才，這也大致符合國際趨勢。蔡總統還說，稅改還讓一般所得者有比較大扣除額，如果受薪者和一般所得者的稅負擔減輕，增加可支配所得，生活安全感更好一點，比較願意消費。（政治中心／台北報導）'''

In [68]:
import jieba
jieba.add_word('朱敬一')
words = []
for w in jieba.cut(article):
    words.append(w)

In [70]:
from collections import Counter
c = Counter(words)
for rec in c.most_common(30):
    if len(rec[0]) >= 2:
        print(rec[0], rec[1])

企業 6
稅改 5
負擔 5
減輕 4
一般 4
所得者 4
蔡總統 4
所得 4
指出 3
整體 3
不能 3
中小 3
經濟 3
需要 3
因此 3
朱敬一 2


In [77]:
import math
a , abb, abc = ['a'],['a', 'b', 'b'], ['a','b', 'c']
D = [a,abb,abc]
#tfidf('a', a, D)
tf  = 1/1
idf = math.log(3/ 3)
tf * idf 

0.0

In [78]:
# tfuidf('a', abb, D)
tf = 1/3
idf = math.log(3/3)
tf * idf 

0.0

In [81]:
# tfidf('b', abb, D)
tf = 2/3
idf = math.log(3/2)
print(tf * idf)

0.27031007207210955


In [82]:
# tfidf('b', abc D)
tf = 1/3
idf = math.log(3/2)
print(tf * idf)

0.13515503603605478


In [85]:
# tfidf ('c', abc, D)
tf = 1/3
idf = math.log(3/1)
print(tf*idf)

0.3662040962227032


In [ ]:
import scipy as sp
def tfidf(t, d, D):
    tf = float(d.count(t)) / sum(d.count(w) for w in set(d))
    idf = sp.log(float(len(D)) / (len([doc for doc in D if t in doc])))
    return tf * idf


## 詞頻矩陣

In [86]:
import jieba
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']

corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))


In [88]:
corpus

['【 更新 】 柯P ： 洪智坤 洩漏 公文 案還 沒 看到 公文 \u3000 今處理',
 '留 洪智坤   柯 ： 殘障 求職 不易',
 '人事處 議處 洪智坤 \u3000 柯P ： 不 清楚 議處 結果']

In [91]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer  = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
X.toarray()

['不易', '人事處', '今處理', '公文', '更新', '柯p', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '看到', '結果', '議處']


array([[0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2]], dtype=int64)

In [93]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer  = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
X.toarray()[0]

['不易', '人事處', '今處理', '公文', '更新', '柯p', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '看到', '結果', '議處']


array([ 0.        ,  0.        ,  0.31738473,  0.63476946,  0.31738473,
        0.24137927,  0.31738473,  0.        ,  0.        ,  0.31738473,
        0.18745253,  0.        ,  0.31738473,  0.        ,  0.        ])

In [101]:
import numpy as np
import math
from sklearn.metrics.pairwise import euclidean_distances
v1 = [1,1,0,1,0]
v2 = [0,0,1,0,1]
a = np.array([v1, v2])
euclidean_distances(a)
a1 = np.array(v1)
a2 = np.array(v2)

math.sqrt(sum((a1 - a2) * (a1 - a2)))

2.23606797749979

In [102]:
# 柯文哲 趙藤雄 ......
v1 = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
v2 = [1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
a1 = np.array(v1)
a2 = np.array(v2)
math.sqrt(sum((a1 - a2) * (a1 - a2)))

4.242640687119285

In [104]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity
v1 = [1,1,0,1,0]
v2 = [0,0,1,0,1]
a = np.array([v1, v2])
cosine_distances(a)
cosine_similarity(a)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [105]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']
vectorizer  = CountVectorizer()
X = vectorizer.fit_transform(corpus)
cosine_similarity(X.toarray())

array([[ 1.        ,  0.15075567,  0.20100756],
       [ 0.15075567,  1.        ,  0.16666667],
       [ 0.20100756,  0.16666667,  1.        ]])

## 蘋果新聞搜集

In [106]:
import requests
from bs4 import BeautifulSoup
from datetime import datetime

In [108]:
domain = 'http://www.appledaily.com.tw'


def getDetail(detail_url):
    res = requests.get(detail_url)
    soup = BeautifulSoup(res.text, 'html.parser')
    title   = soup.select('#h1')[0].text
    content = soup.select('#summary')[0].text
    dt      = soup.select('.gggs time')[0].text
    dt      = datetime.strptime(dt, '%Y年%m月%d日%H:%M')
    clicked = soup.select('.clicked')[0].text if len(soup.select('.clicked')) > 0 else 0 
    dic     = {'title': title, 'content': content, 'time':dt, 'clicked':clicked}
    return dic

In [109]:
def getPage(list_url):
    res = requests.get(list_url)
    soup = BeautifulSoup(res.text, 'html.parser')

    newsary = []
    for rec in soup.select('.rtddt a'):
        ret      = {}
        #title    = rec.select('h1')[0].text
        ret['category'] = rec.select('h2')[0].text
        #dt       = rec.select('time')[0].text
        link     = domain + rec['href']
        ret['url'] = link
        detail   = getDetail(link)
        ret.update(detail)
        newsary.append(ret)
    return newsary

In [111]:
list_url = 'http://www.appledaily.com.tw/realtimenews/section/new/{}'
applenews = []
for page in range(1,35):
    print(page)
    ret = getPage(list_url.format(page))    
    applenews.extend(ret)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34


In [112]:
import pandas
appledf = pandas.DataFrame(applenews)
appledf.to_excel('20171003_applenews.xlsx')

## 讀取蘋果新聞

In [114]:
import pandas
df = pandas.read_excel('20171003_applenews.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1020 entries, 0 to 1019
Data columns (total 6 columns):
category    1020 non-null object
clicked     1020 non-null object
content     1020 non-null object
time        1020 non-null datetime64[ns]
title       1020 non-null object
url         1020 non-null object
dtypes: datetime64[ns](1), object(5)
memory usage: 55.8+ KB


In [116]:
import jieba
corpus = []
titles = []

for news in df.iterrows():
    corpus.append(' '.join(jieba.cut(news[1].content)))
    titles.append(news[1].title)

In [173]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [117]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer  = CountVectorizer()
X = vectorizer.fit_transform(corpus)

X.shape

(1020, 41918)

In [118]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity
cosine_similarities = cosine_similarity(X.toarray())

In [142]:
def getSimiliarNews(idx):
    print('查詢新聞:', titles[idx])
    for pos in cosine_similarities[idx].argsort()[::-1][1:10]:
        print('相關新聞',titles[pos], cosine_similarities[idx][pos])
getSimiliarNews(19)

查詢新聞: 快艇「歐洲球王」首出賽只得一分　隊友：他的傳球才是重點
相關新聞 快艇「歐洲魔術師」特多希奇NBA熱身賽首秀8助攻 0.253203770771
相關新聞 【有片】陳盈駿成為第3位在NBA熱身賽得分的台灣球員 0.230957923299
相關新聞 就算爾文加盟　塞爾提克還是不打算任命隊長 0.194551965525
相關新聞 有機會再奪投手三冠王　羅力：沒打季後賽很失望 0.189589733775
相關新聞 【有片】諾佬再度降薪挺小牛　球迷感激奉上20美元請午餐 0.173718277662
相關新聞 【有片】76人選秀狀元西蒙斯預約強勢復出 0.170232969835
相關新聞 向中國喊話　蔡英文：19大後可思考新模式讓兩岸更活絡 0.137944106665
相關新聞 法官首度打季後賽　拚了一整年就是為了冠軍戒 0.134966175691
相關新聞 關鍵期獅隊2投手小拉傷　蔗總：不會讓他們硬上 0.129724403257


In [144]:
def getSimiliarNews2(idx, threshold):
    print('查詢新聞:', titles[idx])
    for pos in cosine_similarities[idx].argsort()[::-1]:
        if cosine_similarities[idx][pos] > threshold:
            print('相關新聞',titles[pos], cosine_similarities[idx][pos])
getSimiliarNews2(30, 0.2)

查詢新聞: 賭城駭人槍擊　可能是美首宗用自動槍的大規模槍擊案
相關新聞 賭城駭人槍擊　可能是美首宗用自動槍的大規模槍擊案 1.0
相關新聞 【不斷更新】男賭城濫射　激增至58死逾500傷 0.286112018477
相關新聞 賭城孤狼槍手飲彈自盡　飯店房裡搜到10把槍 0.276381909548
相關新聞 【不斷更新】賭城59死大屠殺　槍手擁42把槍如軍火庫 0.269132971142
相關新聞 【驚悚現場】槍彈狂掃射　全場趴下不敢動 0.239266100085
相關新聞 【有片】槍聲不斷　美槍擊案民眾驚叫逃竄 0.210321802986
相關新聞 【快逃】「槍聲響不停」　賭城民眾驚險逃生影片曝光 0.203161880818


## 文章分群

In [174]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
weight = tfidf.toarray() 


In [179]:
from sklearn import cluster
c = cluster.KMeans(n_clusters=20)
k_data = c.fit_predict(weight)

In [180]:
X.shape

(1020, 41918)

In [192]:
np_titles[k_data  == 1]

array(['吉米基墨哽咽開場：美國被擁槍遊說團統治', '賭城駭人槍擊\u3000可能是美首宗用自動槍的大規模槍擊案',
       '【賭城大屠殺】古巨基親述亡命6小時\u3000藏匿其他旅客房', '美國賭城大屠殺\u3000外交部：已向美方表達慰問與關懷',
       '【賭城大屠殺】生死交關5分鐘\u3000靠「金手指」救命', '中國大老闆遇賭城大屠殺\u3000「練跑步很有用」',
       '「以為是鞭炮」外媒拍下槍擊現場令人鼻酸\u3000', '\u200b美國槍枝不管制 讓國民死在自己土地上 ',
       '【不斷更新】賭城59死大屠殺\u3000槍手擁42把槍如軍火庫', '臉書嘲諷槍擊案死者不值得同情\u3000CBS高層遭炒',
       'IS宣稱犯下賭城血案\u3000專家指疑點重重', '曾是槍擊案受害者！連勝文聞賭城槍案這樣說',
       '賭城大屠殺59死\u3000王力宏籲禁槍「要多少無辜丟命」',
       '花蝴蝶「貴妃姿勢」談賭城槍擊慘案\u3000網友傻眼貓咪\u3000', '賭城槍手反川普？\u3000右翼網站操弄假新聞',
       '美賭城槍擊案死傷慘重\u3000蔡英文：譴責暴力', '【懺悔片】支持擁槍者親歷屠殺才後悔\u3000「無法形容過去錯誤」',
       '\u200b孔令信專欄：賭城屠殺 川普被自己人打臉', '【賭城直擊】他出差遇到槍擊案\u3000出事酒店一度封鎖',
       '賭城槍擊案\u3000我舊金山辦事處協尋失聯台人', '【有片】因應美國賭城槍擊案\u3000航警局加強桃機維安',
       '【有片】因應美國賭城槍擊案\u3000航警局加強桃機維安', '【賭城大屠殺】加州民主黨領袖：槍管法需儘快修訂',
       '【蘋果直擊】賭城生還者談救人：襲擊中互助令人動容', '黃金周四川團賭城驚魂\u3000「美劇槍擊情景重現」',
       '賭城槍擊案後\u3000美國再掀槍枝管制論戰', '屠殺掃射速度驚人\u3000槍手可能加了特殊裝置',
       '賭城槍擊美史上最慘\u3000護理師、軍警都遇害', '【集氣片】明星齊悼賭城槍擊案\u3000民眾大排長龍踴躍捐血',
       '【賭城大屠殺】兇嫌弟：我

## 新聞分類

In [ ]:
import pandas
df = pandas.read_excel('20171003_applenews.xlsx')
df.info()

In [224]:
import jieba
corpus = []
titles = []
target = []
for news in df.iterrows():
    if news[1].category in ['娛樂', '社會', '財經']:
        corpus.append(' '.join(jieba.cut(news[1].content)))
        titles.append(news[1].title)
        target.append(news[1].category)

In [225]:
from sklearn.feature_extraction.text import TfidfVectorizer
transformer = TfidfVectorizer()
tfidf = transformer.fit_transform(corpus)
weight = tfidf.toarray() 

In [236]:
?train_test_split

In [240]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(weight, target)

In [247]:
train_X.shape
len(train_y)
test_X.shape
len(test_y)

88

In [248]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=0.01)
clf.fit(train_X,train_y)

MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True)

In [243]:
predicted = clf.predict(test_X)

In [244]:
test_target = np.array(test_y)
sum(predicted == test_target)/ len(test_target)

0.97727272727272729

In [245]:
from sklearn.metrics import confusion_matrix
print(clf.classes_)
confusion_matrix(predicted, test_target)

['娛樂' '社會' '財經']


array([[31,  1,  1],
       [ 0, 33,  0],
       [ 0,  0, 22]])

In [249]:
predicted2 = clf.predict(weight)

In [250]:
test_target2 = np.array(target)

In [252]:
np_titles = np.array(titles)
#for ele in np_titles[predicted != test_target]:
#    print(ele)
for idx, res in enumerate(predicted2 != test_target2):
    if res == True:
        print(np_titles[idx], predicted2[idx], test_target2[idx])

【K律師論點】從乃哥飆罵從從　看正義感的強弱 娛樂 社會
JR東日本鐵道便當爭霸　特樂通邀訪日旅客​票選抽好禮 娛樂 財經


## argsort

In [123]:
import numpy as np
a = np.array([180,167,173,154,172])
a.argsort()
a.argsort()[::-1]


array([0, 2, 4, 1, 3], dtype=int64)