## 建立英文詞頻矩陣

In [4]:
content = ['How to format my hard disk','Hard disk format problems']

from sklearn.feature_extraction.text import CountVectorizer
#?CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(content)
X

<2x7 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [6]:
print(vectorizer.get_feature_names())
X.toarray()

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']


array([[1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [13]:
content = ['How to format my hard disk',\
           'Hard disk format problems', \
           'How hard is this problem']

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=2)
X = vectorizer.fit_transform(content)
X

<3x4 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [14]:
print(vectorizer.get_feature_names())
X.toarray()

['disk', 'format', 'hard', 'how']


array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 1, 1]], dtype=int64)

## 規則模型

In [18]:
Q = '金早安全出現問題'
A = '您也早安' if '早安' in Q else '我不知道你在說什麼'
A

'您也早安'

## 利用詞頻矩陣做資料檢索

In [22]:
%ls data\toy

 磁碟區 C 中的磁碟是 OS 7
 磁碟區序號:  C485-A13C

 C:\Users\User\pytextmining\data\toy 的目錄

2015/10/12  上午 10:25    <DIR>          .
2015/10/12  上午 10:25    <DIR>          ..
2015/10/12  上午 10:25                92 01.txt
2015/10/12  上午 10:25                47 02.txt
2015/10/12  上午 10:25                47 03.txt
2015/10/12  上午 10:25                29 04.txt
2015/10/12  上午 10:25                89 05.txt
               5 個檔案             304 位元組
               2 個目錄  10,980,343,808 位元組可用


In [30]:
import os
path = 'data/toy/'
posts = []
for fname in os.listdir(path):
    with open(path + fname) as f:
        posts.append(f.read())

In [31]:
posts

['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [32]:
posts = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
 'Imaging databases provide storage capabilities.',
 'Most imaging databases safe images permanently.',
 'Imaging databases store data.',
 'Imaging databases store data. Imaging databases store data. Imaging databases store data.']

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df = 1)
X_train = vectorizer.fit_transform(posts)
X_train

<5x25 sparse matrix of type '<class 'numpy.int64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [48]:
X_train.shape

(5, 25)

In [49]:
print(vectorizer.get_feature_names())
X_train.toarray()

['about', 'actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'this', 'toy']


array([[1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0],
       [0, 0, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0]], dtype=int64)

In [80]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])
new_post_vec

<1x25 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [81]:
print(vectorizer.get_feature_names())
new_post_vec.toarray()

['about', 'actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'this', 'toy']


array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]], dtype=int64)

In [62]:
import scipy as sp
def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta)

In [74]:
import numpy as np
import math
v1 = np.array([1,0,0,1,1])
v2 = np.array([1,1,0,0,1])
math.sqrt(((v2 - v1) ** 2).sum())

1.4142135623730951

In [75]:
dist_raw(v1, v2)

1.4142135623730951

In [76]:
import scipy as sp
def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray())

In [82]:
import sys
best_doc = None
best_dist = 999
best_i = None

num_samples = len(posts)
for i in range(0, num_samples):
    post = posts[i]
    if post==new_post:
        continue
    post_vec = X_train.getrow(i)
    d = dist_raw(post_vec, new_post_vec)
    print("=== Post %i with dist=%.2f: %s"%(i, d, post))
    if d<best_dist:
        best_dist = d
        best_i = i
print("Best post is %i with dist=%.2f"%(best_i, best_dist))

=== Post 0 with dist=3.87: This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=2.00: Imaging databases provide storage capabilities.
=== Post 2 with dist=2.24: Most imaging databases safe images permanently.
=== Post 3 with dist=1.73: Imaging databases store data.
=== Post 4 with dist=5.57: Imaging databases store data. Imaging databases store data. Imaging databases store data.
Best post is 3 with dist=1.73


In [83]:
def dist(v1, v2):
    v1_normalized  = v1 / sp.linalg.norm(v1.toarray()) 
    v2_normalized  = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [84]:
import sys
best_doc = None
best_dist = 999
best_i = None

num_samples = len(posts)
for i in range(0, num_samples):
    post = posts[i]
    if post==new_post:
        continue
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print("=== Post %i with dist=%.2f: %s"%(i, d, post))
    if d<best_dist:
        best_dist = d
        best_i = i
print("Best post is %i with dist=%.2f"%(best_i, best_dist))

=== Post 0 with dist=1.41: This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=1.05: Imaging databases provide storage capabilities.
=== Post 2 with dist=1.09: Most imaging databases safe images permanently.
=== Post 3 with dist=1.00: Imaging databases store data.
=== Post 4 with dist=1.00: Imaging databases store data. Imaging databases store data. Imaging databases store data.
Best post is 3 with dist=1.00


## NLTK Stemming

In [85]:
! pip install nltk

In [87]:
import nltk.stem
s = nltk.stem.SnowballStemmer('english')
s.stem('graphics')

'graphic'

In [89]:
print(s.stem("imaging"))
print(s.stem("image"))
print(s.stem("imagination"))
print(s.stem("imagine"))

imag
imag
imagin
imagin


In [95]:
import nltk.stem
english_stemmer = nltk.stem.SnowballStemmer('english')

class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))


## 移除Stopwords

In [96]:
#vectorizer = CountVectorizer()
#vectorizer = CountVectorizer(stop_words=['it'])
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())

['actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'learning', 'machine', 'permanently', 'post', 'provide', 'safe', 'storage', 'store', 'stuff', 'toy']


In [104]:
vectorizer = StemmedCountVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(posts)
print(vectorizer.get_feature_names())

['actual', 'capabl', 'contain', 'data', 'databas', 'imag', 'interest', 'learn', 'machin', 'perman', 'post', 'provid', 'safe', 'storag', 'store', 'stuff', 'toy']


In [105]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])
new_post_vec

<1x17 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [106]:
import sys
best_doc = None
best_dist = 999
best_i = None

num_samples = len(posts)
for i in range(0, num_samples):
    post = posts[i]
    if post==new_post:
        continue
    post_vec = X_train.getrow(i)
    d = dist(post_vec, new_post_vec)
    print("=== Post %i with dist=%.2f: %s"%(i, d, post))
    if d<best_dist:
        best_dist = d
        best_i = i
print("Best post is %i with dist=%.2f"%(best_i, best_dist))

=== Post 0 with dist=1.41: This is a toy post about machine learning. Actually, it contains not much interesting stuff.
=== Post 1 with dist=0.86: Imaging databases provide storage capabilities.
=== Post 2 with dist=0.63: Most imaging databases safe images permanently.
=== Post 3 with dist=0.77: Imaging databases store data.
=== Post 4 with dist=0.77: Imaging databases store data. Imaging databases store data. Imaging databases store data.
Best post is 2 with dist=0.63
